In [ ]:
6CS012 - Artificial Intelligence and Machine Learning.
A Tutorial and Assessment on Python and NumPy for Deep

In [ ]:
Name:Hemanta Raj Pandey
Student Number: 23357629

In [ ]:
Task - 1: 

In [ ]:
# Unit Conversion Program in Jupyter Notebook

def length_conversion(value, unit):
    if unit == "m":
        return value * 3.28084  # Meters to feet
    elif unit == "ft":
        return value / 3.28084  # Feet to meters
    else:
        raise ValueError("Unsupported length unit. Use 'm' or 'ft'.")

def weight_conversion(value, unit):
    if unit == "kg":
        return value * 2.20462  # Kg to lbs
    elif unit == "lbs":
        return value / 2.20462  # Lbs to kg
    else:
        raise ValueError("Unsupported weight unit. Use 'kg' or 'lbs'.")

def volume_conversion(value, unit):
    if unit == "L":
        return value * 0.264172  # Liters to gallons
    elif unit == "gal":
        return value / 0.264172  # Gallons to liters
    else:
        raise ValueError("Unsupported volume unit. Use 'L' or 'gal'.")

def main():
    print("Unit Conversion Program")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")
    
    try:
        choice = int(input("Choose conversion type (1-3): "))
        value = float(input("Enter the value to convert: "))
        
        if choice == 1:
            unit = input("Enter unit (m or ft): ").strip().lower()
            converted_value = length_conversion(value, unit)
            new_unit = "ft" if unit == "m" else "m"
        
        elif choice == 2:
            unit = input("Enter unit (kg or lbs): ").strip().lower()
            converted_value = weight_conversion(value, unit)
            new_unit = "lbs" if unit == "kg" else "kg"
        
        elif choice == 3:
            unit = input("Enter unit (L or gal): ").strip().lower()
            converted_value = volume_conversion(value, unit)
            new_unit = "gal" if unit == "L" else "L"
        
        else:
            print("Invalid choice! Please select 1, 2, or 3.")
            return
        
        print(f"{value} {unit} is equal to {converted_value:.2f} {new_unit}")
    
    except ValueError as e:
        print(f"Error: {e}")


main()


Unit Conversion Program
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)


Choose conversion type (1-3):  2
Enter the value to convert:  5433
Enter unit (kg or lbs):  kg


5433.0 kg is equal to 11977.70 lbs


In [ ]:
Task - 2:

In [ ]:
# Mathematical Operations Program in Jupyter Notebook

def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def get_number_list():
    while True:
        try:
            numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
            if not numbers:
                raise ValueError("List cannot be empty. Please enter at least one number.")
            return numbers
        except ValueError:
            print("Invalid input! Please enter numbers only.")

def main():
    print("Mathematical Operations Program")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    
    try:
        choice = int(input("Choose an operation (1-4): "))
        numbers = get_number_list()
        
        if choice == 1:
            result = calculate_sum(numbers)
            operation = "Sum"
        elif choice == 2:
            result = calculate_average(numbers)
            operation = "Average"
        elif choice == 3:
            result = find_maximum(numbers)
            operation = "Maximum"
        elif choice == 4:
            result = find_minimum(numbers)
            operation = "Minimum"
        else:
            print("Invalid choice! Please select 1, 2, 3, or 4.")
            return
        
        print(f"{operation} of {numbers} is: {result:.2f}")
    
    except ValueError:
        print("Error: Invalid input! Please enter a valid number.")


main()


Mathematical Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum


Choose an operation (1-4):  4
Enter numbers separated by spaces:  2 3 4 5 


Minimum of [2.0, 3.0, 4.0, 5.0] is: 2.00


In [ ]:
4.2 Exercise on List Manipulation:

In [18]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    return lst[::2]

# 2. Slice a Sublist
def get_sublist(lst, start, end):
    return lst[start:end+1]

# 3. Reverse a List Using Slicing
def reverse_list(lst):
    return lst[::-1]

# 4. Remove the First and Last Elements
def remove_first_last(lst):
    return lst[1:-1]

# 5. Get the First n Elements
def get_first_n(lst, n):
    return lst[:n]

# 6. Extract Elements from the End
def get_last_n(lst, n):
    return lst[-n:]

# 7. Extract Elements in Reverse Order
def reverse_skip(lst):
    return lst[-2::-2]

# Test examples
test_list = [1, 2, 3, 4, 5, 6]

print("1. Extract Every Other Element:", extract_every_other(test_list)) 
print("2. Slice a Sublist (from index 2 to 4):", get_sublist(test_list, 2, 4)) 
print("3. Reverse the List:", reverse_list(test_list)) 
print("4. Remove First and Last Elements:", remove_first_last(test_list)) 
print("5. Get the First 3 Elements:", get_first_n(test_list, 3))
print("6. Get the Last 2 Elements:", get_last_n(test_list, 2))  
print("7. Extract Elements in Reverse Order:", reverse_skip(test_list)) 


1. Extract Every Other Element: [1, 3, 5]
2. Slice a Sublist (from index 2 to 4): [3, 4, 5]
3. Reverse the List: [6, 5, 4, 3, 2, 1]
4. Remove First and Last Elements: [2, 3, 4, 5]
5. Get the First 3 Elements: [1, 2, 3]
6. Get the Last 2 Elements: [5, 6]
7. Extract Elements in Reverse Order: [5, 3, 1]


In [ ]:
4.3 Exercise on Nested List:

In [13]:
# list_operations.py

# 1. Flatten a Nested List
def flatten(lst):
    """Flattens a nested list into a single dimension."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item)) 
        else:
            flat_list.append(item)
    return flat_list


# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    """Extracts an element from a nested list based on a list of indices."""
    for index in indices:
        lst = lst[index]
    return lst


# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """Calculates the sum of all elements in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(i, elem) for i in lst if i != elem]
    return lst


# 5. Find the Maximum Element in a Nested List
def find_max(lst):
    """Finds the maximum element in a nested list."""
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))  
        else:
            max_val = max(max_val, item)
    return max_val


# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  
        elif item == elem:
            count += 1
    return count


# 7. Flatten a List of Lists of Lists
def deep_flatten(lst):
    """Flattens a deeply nested list into a single dimension."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item)) 
        else:
            flat_list.append(item)
    return flat_list


# 8. Nested List Average
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    total = sum_nested(lst)
    count = sum(1 for _ in flatten(lst))
    return total / count if count > 0 else 0



# Test Cases for Each Function
print(flatten([[1, 2], [3, 4], [5]])) 
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2])) 
print(sum_nested([[1, 2], [3, [4, 5]], 6])) 
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  
print(find_max([[1, 2], [3, [4, 5]], 6])) 
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])) 
print(average_nested([[1, 2], [3, 4], [5, 6]])) 


[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


In [ ]:
10.1 Basic Vector and Matrix Operation with Numpy.

In [ ]:
Problem - 1: Array Creation:

In [14]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll ones array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value = 7
filled_array = np.full((3, 3), fill_value)
print("\nArray filled with value 7 (3x3):")
print(filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)
print("\nArray of zeros with the same shape as the example array:")
print(zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("\nArray of ones with the same shape as the example array:")
print(ones_like_array)

# 6. Convert the list [1, 2, 3, 4] to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted numpy array from the list [1, 2, 3, 4]:")
print(numpy_array)


Empty array (2x2):
[[0.00000000e+000 1.40410014e-311]
 [1.40410014e-311 1.40410014e-311]]

All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros with the same shape as the example array:
[[0 0]
 [0 0]]

Array of ones with the same shape as the example array:
[[1 1]
 [1 1]]

Converted numpy array from the list [1, 2, 3, 4]:
[1 2 3 4]


In [ ]:
Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [15]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_random_array = random_array.mean()
print("\nRandom array of size 30 and its mean:")
print(random_array)
print("Mean:", mean_random_array)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 array with random values, minimum and maximum:")
print(random_10x10)
print("Min:", min_value, "Max:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  
print("\nZero array with 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:")
print(reversed_arr)

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:")
print(border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1 
checkerboard[::2, 1::2] = 1
print("\n8x8 matrix with a checkerboard pattern:")
print(checkerboard)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30 and its mean:
[0.93123368 0.63950851 0.29242784 0.53065633 0.52886274 0.50500197
 0.6034728  0.59043901 0.88374798 0.06146583 0.61116198 0.27648354
 0.97510334 0.59336146 0.75766804 0.01756063 0.60456879 0.02774485
 0.8981015  0.50088254 0.01004922 0.83451788 0.67631343 0.62895786
 0.62969164 0.29713577 0.85489077 0.21011441 0.55701903 0.76507474]
Mean: 0.5431072711414028

10x10 array with random values, minimum and maximum:
[[0.05861089 0.68193576 0.10704522 0.89080597 0.49303265 0.50238555
  0.07960892 0.10173298 0.72266728 0.62072992]
 [0.34311222 0.11453077 0.8163802  0.0664342  0.2151715  0.14306739
  0.34959679 0.48226989 0.79594711 0.47309248]
 [0.97931759 0.10620385 0.14549847 0.37183954 0.

In [ ]:
Problem - 3: Array Operations:

In [16]:
import numpy as np

# Arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition_result = x + y
print("Addition of x and y:")
print(addition_result)

# 2. Subtract the two arrays
subtraction_result = x - y
print("\nSubtraction of x and y:")
print(subtraction_result)

# 3. Multiply the array with any integers of your choice
multiply_result = x * 2  
print("\nMultiplication of x with integer 2:")
print(multiply_result)

# 4. Find the square of each element of the array
square_result = np.square(x)
print("\nSquare of each element in x:")
print(square_result)

# 5. Find the dot product between:
# v and w
dot_vw = np.dot(v, w)
# x and v
dot_xv = np.dot(x, v)
# x and y
dot_xy = np.dot(x, y)
print("\nDot product between v and w:", dot_vw)
print("Dot product between x and v:", dot_xv)
print("Dot product between x and y:", dot_xy)

# 6. Concatenate x and y along row and Concatenate v and w along column
concat_xy_row = np.concatenate((x, y), axis=0)  
concat_vw_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  
print("\nConcatenation of x and y along row:")
print(concat_xy_row)
print("\nConcatenation of v and w along column:")
print(concat_vw_column)

# 7. Concatenate x and v; if an error occurs, explain the reason
try:
    concat_xv = np.concatenate((x, v), axis=0)  
    print("\nConcatenation of x and v:")
    print(concat_xv)
except Exception as e:
    print("\nError while concatenating x and v along row:", e)


Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x with integer 2:
[[ 2  4]
 [ 6 10]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product between v and w: 219
Dot product between x and v: [29 77]
Dot product between x and y: [[19 22]
 [50 58]]

Concatenation of x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along column:
[[ 9 11]
 [10 12]]

Error while concatenating x and v along row: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
 -> Yes, I got the error because the arrays `x` (a 2D array with shape `(2, 2)`) and `v` (a 1D array with shape `(2,)`) have different numbers
of dimensions. NumPy requires the arrays to have the same number of dimensions for concatenation along a specific axis. Since `x` is 2D and `v` is 1D
, NumPy cannot concatenate them along the row axis (axis=0) directly.

In [ ]:
Problem - 4: Matrix Operations:

In [17]:
import numpy as np

# Problem 1: Prove A * A^(-1) = I
A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)  # Compute the inverse of A
I = np.dot(A, A_inv)  # Multiply A and A_inv to get the identity matrix

print("Problem 1: A * A^(-1) = I")
print("A * A^(-1) = \n", I)
print("\n")

# Problem 2: Prove AB != BA
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("Problem 2: Prove AB != BA")
print("AB = \n", AB)
print("BA = \n", BA)
print("\n")

# Problem 3: Prove (AB)^T = B^T * A^T
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("Problem 3: Prove (AB)^T = B^T * A^T")
print("(AB)^T = \n", AB_T)
print("B^T * A^T = \n", BT_AT)
print("\n")

# Problem 4: Solve the system of Linear equations using Inverse Methods
# The system of equations is:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# Represent the system in matrix form AX = B
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])

# Solve for X using the inverse method: X = A_inv * B
A_inv_system = np.linalg.inv(A_system)  
X_solution = np.dot(A_inv_system, B_system)  

print("Problem 4: Solve the system of Linear equations using Inverse Methods")
print("Solution for x, y, z: ", X_solution)
print("\n")

# Problem 5: Solve the system using np.linalg.inv
X_solution_linalg = np.linalg.solve(A_system, B_system)  

print("Problem 5: Solve the system using np.linalg.inv")
print("Solution using np.linalg.solve: ", X_solution_linalg)


Problem 1: A * A^(-1) = I
A * A^(-1) = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


Problem 2: Prove AB != BA
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]


Problem 3: Prove (AB)^T = B^T * A^T
(AB)^T = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]


Problem 4: Solve the system of Linear equations using Inverse Methods
Solution for x, y, z:  [ 2.  1. -2.]


Problem 5: Solve the system using np.linalg.inv
Solution using np.linalg.solve:  [ 2.  1. -2.]


In [ ]:
10.2 Experiment: How Fast is Numpy?

In [ ]:
import time
import numpy as np

# 1. Element-wise Addition
# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(len(list1))]
python_list_add_time = time.time() - start_time
print(f"Element-wise addition using Python lists took: {python_list_add_time:.6f} seconds")

# Using NumPy Arrays
np_array1 = np.arange(1000000)
np_array2 = np.arange(1000000)
start_time = time.time()
np_sum = np_array1 + np_array2
numpy_add_time = time.time() - start_time
print(f"Element-wise addition using NumPy arrays took: {numpy_add_time:.6f} seconds")

# 2. Element-wise Multiplication
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(len(list1))]
python_list_multiply_time = time.time() - start_time
print(f"Element-wise multiplication using Python lists took: {python_list_multiply_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
np_multiplication = np_array1 * np_array2
numpy_multiply_time = time.time() - start_time
print(f"Element-wise multiplication using NumPy arrays took: {numpy_multiply_time:.6f} seconds")

# 3. Dot Product
# Using Python Lists
start_time = time.time()
dot_product_python = sum(list1[i] * list2[i] for i in range(len(list1)))
python_dot_time = time.time() - start_time
print(f"Dot product using Python lists took: {python_dot_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(np_array1, np_array2)
numpy_dot_time = time.time() - start_time
print(f"Dot product using NumPy arrays took: {numpy_dot_time:.6f} seconds")

# 4. Matrix Multiplication
# Using Python Lists
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]
start_time = time.time()
matrix_multiply_python = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
python_matrix_multiply_time = time.time() - start_time
print(f"Matrix multiplication using Python lists took: {python_matrix_multiply_time:.6f} seconds")

# Using NumPy Arrays
np_matrix1 = np.arange(1000000).reshape(1000, 1000)
np_matrix2 = np.arange(1000000, 0, -1).reshape(1000, 1000)
start_time = time.time()
matrix_multiply_numpy = np.dot(np_matrix1, np_matrix2)
numpy_matrix_multiply_time = time.time() - start_time
print(f"Matrix multiplication using NumPy arrays took: {numpy_matrix_multiply_time:.6f} seconds")


Element-wise addition using Python lists took: 0.232949 seconds
Element-wise addition using NumPy arrays took: 0.000000 seconds
Element-wise multiplication using Python lists took: 0.291769 seconds
Element-wise multiplication using NumPy arrays took: 0.004531 seconds
Dot product using Python lists took: 0.280755 seconds
Dot product using NumPy arrays took: 0.002879 seconds
